# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: "toShade" # optional
      - run: cd /home/runner/work/discord4j-shaded/discord4j-shaded/toShade
      - name: Install Package
        # You may pin to the exact commit or the version.
        # uses: ConorMacBride/install-package@9aadf699d40a59f4eb15355d93122d2fbd7428c9
        uses: ConorMacBride/install-package@v1.0.0
        with:
          # Packages to install with apt on Linux
          apt: openjdk-17-jdk
      - run: wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
      - run: unzip gradle-7.4.2-bin.zip
      - run: ./gradle-7.4.2/bin/gradle -b /home/runner/work/discord4j-shaded/discord4j-shaded/toShade/build.gradle shadowJar
      - name: Upload the shaded jar
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: discord4j-shaded-most.jar # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: "/home/runner/work/discord4j-shaded/discord4j-shaded/toShade/build/libs/discord4j-shaded-all.jar"
